version: '3.8'

services:
  api:
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

  nginx:
    ports:
      - "8080:80" 