version: '3.8'

services:
  # HTML to PDF API Server (Development)
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: html-to-pdf-api-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - app-network
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  # Nginx Reverse Proxy (Development)
  nginx:
    image: nginx:alpine
    container_name: html-to-pdf-nginx-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - app-network

  # Redis for caching (Development)
  redis:
    image: redis:alpine
    container_name: html-to-pdf-redis-dev
    restart: unless-stopped
    volumes:
      - redis-data-dev:/data
    networks:
      - app-network
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  # Adminer for database management (optional)
  adminer:
    image: adminer
    container_name: html-to-pdf-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data-dev:
    driver: local 